### ISSUE TITLE
pushplus推送问题

### ISSUE THREAD

**Issue by oilime** [ICE99125/BiliBili_Checkin#10]
是因为URL不一样吗
`Starting new HTTP connection (1): www.pushplus.plus:80
http://www.pushplus.plus:80 "POST /send?token=XXXXXXXXXXXXXXXX HTTP/1.1" 200 None
发送消息失败: 无效的用户token`

显示的pushplus推送url为www.pushplus.plus，实际应该是pushplus.hxtrip.com，我自己修改之后可以推送成功了

**Comment by ICE99125** [comment]
你这个是盗版推送加官网吧…
我记得推送加官网只有www.pushplus.plus

**Comment by oilime** [comment]
哈哈哈哈还真是，主要是用习惯了就没换。。。
