### ISSUE TITLE
提示：“失败, 原因: 账号异常，操作失败”

### ISSUE THREAD

**Issue by s0k** [ICE99125/BiliBili_Checkin#16]
您好，我通过登录账户，输入 `document.cookie` ,获取`cookie` 后，放到 `config.py`中，

测试运行的时候提示`”失败, 原因: 账号异常，操作失败“`

 `config.py` 的` cookie ` 部分如下
```
{
            "cookie": "blackside_state=1; rpdid=|(J|)JkYlkYY0J'uY|muYluR~; xxxxxxxxx; bili_jct=xxx; b_ut=5",
            "options": {
                "watch": True,  # 每日观看视频
                "coins": 2,  # 投币个数
                "share": True,  # 视频分享
                "comics": True,  # 漫画签到
                "lb": True,  # 直播签到
            },
```

报错如下：

```
开头：
Invoke function bilibili [RequestId:e137d71d-ff32-4727-808b-808b1a15f6ef]
Response: 
null
Output:
START RequestId: e137d71d-ff32-4727-808b-808b1a15f6ef
Event RequestId: e137d71d-ff32-4727-808b-808b1a15f6ef
ace/share/add HTTP/1.1" 200 63
分享视频[别瞎踢，你不知道草里藏着啥玩意]失败, 原因: 账号异常，操作失败
Starting new HTTPS connection (1): api.bilibili.com:443
https://api.bilibili.com:443 "POST /x/web-interface/share/add HTTP/1.1" 200 63
分享视频[艾尔登法环支线汇总，带你一图看清支线联系！]失败, 原因: 账号异常，操作失败

省略相似报错..........

结尾：
END RequestId: e137d71d-ff32-4727-808b-808b1a15f6ef
Report RequestId: e137d71d-ff32-4727-808b-808b1a15f6ef Duration:12826ms Memory:128MB MemUsage:16.9473MB
Summary:
  Request ID: e137d71d-ff32-4727-808b-808b1a15f6ef
  Run Duration: 12826
  Bill Duration: 12826
  Usage Memory: 16.947303771972656
  Invoke Result: 0

```

**Comment by ICE99125** [comment]
你是账号密码登录的嘛？cookie中是否包含了sid，bili_jct，DedeUserID 这三个字段

**Comment by s0k** [comment]
> 你是账号密码登录的嘛？cookie中是否包含了sid，bili_jct，DedeUserID 这三个字段

对，账号密码登录，包含这三个字段了

**Comment by ICE99125** [comment]
要不你点个赞，然后用这个 cookie 试试，我也不懂了😥
![QQ截图20220305121843](https://user-images.githubusercontent.com/65435402/156867406-447e70c4-8986-49c5-84ce-f2138e4cdc8d.png)

**Comment by ICE99125** [comment]
我突然想起来 document.cookie 可能获取不到一些 httponly 的 cookie，可能是这个原因

**Comment by s0k** [comment]
> 要不你点个赞，然后用这个 cookie 试试，我也不懂了😥 ![QQ截图20220305121843](https://user-images.githubusercontent.com/65435402/156867406-447e70c4-8986-49c5-84ce-f2138e4cdc8d.png)

可以了，就是cookie获取的不对，我换了个浏览器，然后在网络加载里面随便找个cookie就可以了。
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/35159280/156867872-482454d1-e670-491d-a8ef-86f978e7b21a.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/35159280/156867888-bbc41b55-7ade-4351-9030-85e837ed787f.png">

谢谢楼主

**Comment by s0k** [comment]
> 我突然想起来 document.cookie 可能获取不到一些 httponly 的 cookie，可能是这个原因

还有想问一下，点赞、投币这些可以指定UP主吗

**Comment by ICE99125** [comment]
不能，主要是有点小麻烦。。。

**Comment by s0k** [comment]
> 不能，主要是有点小麻烦。。。

好的，感谢

**Comment by beggerlove** [comment]
> 要不你点个赞，然后用这个 cookie 试试，我也不懂了😥
> ![QQ截图20220305121843](https://user-images.githubusercontent.com/65435402/156867406-447e70c4-8986-49c5-84ce-f2138e4cdc8d.png)
> 


安卓可以直接用Alook浏览器获取 登录后找到开发者工具 然后 cookie复制全部 粘贴就可以了
