### ISSUE TITLE
cookie取值

### ISSUE THREAD

**Issue by K032** [ICE99125/BiliBili_Checkin#2]
### cookies的值
需要哪个cookie的值
是bili_jct、SESSDATA、还是全值？

**Comment by K032** [comment]
顺便问下pushplus的key的名称填写

**Comment by ICE99125** [comment]
cookie全部复制过去就行了
pushplus的key就写 key：xxxx

**Comment by K032** [comment]
已全复制cookie还是报错，
**;**的间隔符对吗

**Comment by ICE99125** [comment]
什么意思，您是想多账号嘛？如果是多账号就是 cookie1,cookie2
如果还有问题发个图过来看看

**Comment by K032** [comment]
***@***.***
我从这里复制了cookie的值，进行了填写。

发件人: ***@***.***>
发送时间: 2021年11月25日 20:05
收件人: ***@***.***>
抄送: 「 陈 ***@***.***>; ***@***.***>
主题: Re: [ICE99125/BiliBili_Checkin] cookie取值 (Issue #2)


什么意思，您是想多账号嘛？如果是多账号就是 cookie1,cookie2
如果还有问题发个图过来看看

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FICE99125%2FBiliBili_Checkin%2Fissues%2F2%23issuecomment-979148801&data=04%7C01%7C%7C206c6edc96cd4ded330008d9b00be17e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734387353124648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hHdkoP%2FDzWYrdqaVzxj2kXCtOjXQLs374ZCRIPH14l8%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPMIZIVJHK64VW6WK3VYTPTUNYRAXANCNFSM5IXUQVEA&data=04%7C01%7C%7C206c6edc96cd4ded330008d9b00be17e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734387353134606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B0ghYOBrhHvHO2vtsiMdapgvj1MVWoFpg0Wtqltlpsk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C206c6edc96cd4ded330008d9b00be17e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734387353134606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0Slyl8eqgQyMQ8zeUJloM30n6frSZ86Lz%2FPKP53U9sE%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C206c6edc96cd4ded330008d9b00be17e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734387353144560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L1cNJFAOO%2FbUuI%2FszMzGgTyr0a48GPn3RHJWVhpoFLY%3D&reserved=0>.

**Comment by ICE99125** [comment]
？？？
![20211125201053](https://user-images.githubusercontent.com/65435402/143439572-c94b9bd8-f6ea-4e73-b2dc-f07341e183b8.png)

**Comment by K032** [comment]
对不起，我又厚着脸皮来了
昨天图片未上传成功😅

**Comment by K032** [comment]
<img width="565" alt="屏幕截图 2021-11-26 140842" src="https://user-images.githubusercontent.com/64523426/143536187-9273ec53-c9c1-40e4-b498-59c011baf09c.png">

对不起，我又后者脸皮来了，昨天图片上传失败了😓

**Comment by ICE99125** [comment]
🤣 把cookie发出来不太好吧
应该把错误日志发给我

**Comment by ICE99125** [comment]
另外如果要使用多账户的话需要确保cookies里面没有“,”，否则不能正确取出cookies，如果有的话需要改一下代码，把分隔符改成特殊的符号（即更改Cookies = os.getenv('Cookies').split(',')里面的那个逗号）

**Comment by K032** [comment]
**B站现在的cookie的SESSDATA值中包含','导致了此问题**
### 已解决，谢谢作者大大😎

**Comment by K032** [comment]
![Collage_20211126_164628](https://user-images.githubusercontent.com/64523426/143553285-fe876c45-4018-414b-9f4f-ddc850376040.jpg)

**B站现在的cookie的SESSDATA值中包含','导致了此问题**
### 已解决，谢谢作者大大😎
