### ISSUE TITLE
企业微信推送有些奇怪 跟日志跑的不一样

### ISSUE THREAD

**Issue by 666668113** [ICE99125/BiliBili_Checkin#20]
![屏幕截图 2022-04-14 180309](https://user-images.githubusercontent.com/71271253/163362903-2c0edb74-a242-4f2b-b7b9-cc1c3d96a8ae.png)
![屏幕截图 2022-04-14 180342](https://user-images.githubusercontent.com/71271253/163362990-95a3a795-2a82-4d8f-b660-1529a8a6c4d8.png)
是不是设置哪里错了 agentid  corpSecret  corpid的值可以填写进config文件件中吗？

**Comment by ICE99125** [comment]
你这是哪个界面啊...

**Comment by 666668113** [comment]
> 你这是哪个界面啊...

服务器跑的 挂在青龙里面
![屏幕截图 2022-04-14 183614](https://user-images.githubusercontent.com/71271253/163371486-575d1e7e-dd9a-4fa6-8628-44d0a7ac4465.png)

**Comment by ICE99125** [comment]
这不懂了, 我也没有服务器...我刚才使用腾讯云测试了下没问题

**Comment by 666668113** [comment]
> 这不懂了, 我也没有服务器...我刚才使用腾讯云测试了下没问题
那个 agentid corpSecret corpid的值可以填写进config文件件中吗？

**Comment by ICE99125** [comment]
不是的呀, 是填写到环境变量里的, 这不是这个问题, 主要是推送出现了中文乱码, 也就是推送其实是成功的, 但不知道哪里出现问题了

**Comment by 666668113** [comment]
> 不是的呀, 是填写到环境变量里的, 这不是这个问题, 主要是推送出现了中文乱码, 也就是推送其实是成功的, 但不知道哪里出现问题了

这么说也是啊😂算了主要是server有了次数限制所以才想这用企业微信

**Comment by ICE99125** [comment]
也可以用pushplus呀
