### ISSUE TITLE
[建议]希望能支持账户小于指定投币数就暂停投币

### ISSUE THREAD

**Issue by misaka10843** [ICE99125/BiliBili_Checkin#23]
希望能支持账户小于指定投币数就暂停投币，因为想每天硬币的经验拿满，但是又不想直接花完，想留点硬币，但是程序里面没有可以限制的功能，故此想大佬能做个对应功能qwq

**Comment by ICE99125** [comment]
啥意思...是说当硬币少于多少时即使想投硬币也不能投嘛？

**Comment by ICE99125** [comment]
之前是可以设置投多少个币, 如果想拿满就设置成5个就好了, 每天就只会投5个, 现在新增了一个阈值, 当用户硬币数少于多少时就不会投了

**Comment by misaka10843** [comment]
> 啥意思...是说当硬币少于多少时即使想投硬币也不能投嘛？

的确🤣
感谢大大的更新🤣
