### ISSUE TITLE
不对啊，报错了

### ISSUE THREAD

**Issue by WHmuse** [ICE99125/BiliBili_Checkin#3]
{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 675, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 655, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 678, in exec_module\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 25, in &lt;module;&gt;\n    csrf.append(re.findall('(?&lt;=bili_jct=)(.+?);', i)[0])\nIndexError: list index out of range","requestId":"d7cc4ae6-e476-4e83-957d-dbf3f9d37123","statusCode":443}

**Comment by WHmuse** [comment]
这个是报错的日志

**Comment by ICE99125** [comment]
1. 确保 cookie 里有 bili_jct=xxxx;(有人说必须账号密码登录才行，没有验证)
2. 如果 cookie 里有 ',' 就把 20 行的 Cookies = os.getenv('Cookies').split(',') 里的 ',' 改成特殊的分隔符

**Comment by WHmuse** [comment]
cookie 里是有',' 改成特殊的分隔符改成那个分隔符啊

**Comment by ICE99125** [comment]
改成什么都行，不要出现在 cooike 里就行了，然后使用的时候就用这个符号分割不同 cookie 就行了

**Comment by WHmuse** [comment]
{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 675, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 655, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 678, in exec_module\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 25, in &lt;module;&gt;\n    csrf.append(re.findall('(?&lt;=bili_jct=)(.+?);', i)[0])\nIndexError: list index out of range","requestId":"2da2659c-2f4f-4d8e-bad4-128b2fb6d2b2","statusCode":443}

**Comment by WHmuse** [comment]
还是在报错  我已经吧多账号分隔符改成'-'了

**Comment by ICE99125** [comment]
你确定 cookie 里面没有 - 么
这个错误是因为在 cookie 里找不到 bili_jct 
![QQ截图20211129180848](https://user-images.githubusercontent.com/65435402/143848567-fa36ed19-ab20-4b9a-a654-f2603d5f1488.png)
一个可能就是 cookie 没有分割正确导致的
另一个可能就是 cookie 里面本来就没有

**Comment by WHmuse** [comment]
![image](https://user-images.githubusercontent.com/70631215/143862113-2c4e3440-ded5-4774-ba82-65988b7f6f97.png)

**Comment by WHmuse** [comment]
![image](https://user-images.githubusercontent.com/70631215/143862143-724df862-855f-4b54-b2e6-43258649452a.png)

**Comment by WHmuse** [comment]
你的意思是要cookie里所有的key 和 value么

**Comment by WHmuse** [comment]
ok  原来是要所有key value 现在正常了  多谢解答！！！！  star 奉上！！！

**Comment by WHmuse** [comment]
还有个问题哈  就是刚登录的cookies 日志里就写失效了  这是啥啊

**Comment by WHmuse** [comment]
宝  有考虑做贴吧的签到和自动发帖功能么

**Comment by ICE99125** [comment]
贴吧有签到，发帖没试过
