### ISSUE TITLE
启用观看视频的话就会出现这个错误，不启用的话能用，不知道是不是接口寄了？

### ISSUE THREAD

**Issue by zhuzil** [ICE99125/BiliBili_Checkin#4]
{

  "errorCode": -1,

  "errorMessage": "Invoking task timed out after 3 seconds",

  "requestId": "fae89984-6605-414d-a709-6c39777b5cce",

  "statusCode": 433

}

**Comment by zhuzil** [comment]
哦对了，我本地运行代码，然后自己改了一下的话，好像又能用

**Comment by zhuzil** [comment]
这是执行日志

正在观看视频...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/view?bvid=BV1if4y1g7Qp HTTP/1.1" 200 None

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/click/web/h5 HTTP/1.1" 200 32

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/web/heartbeat HTTP/1.1" 200 32


END RequestId: 1a51b352-6749-4c8b-aaa8-9e54fedc227f

Report RequestId: 1a51b352-6749-4c8b-aaa8-9e54fedc227f Duration:3000ms Memory:128MB MemUsage:29.7305MB

**Comment by ICE99125** [comment]
不晓得了🙃，我还一直在用呀，说明接口没问题

正在观看视频...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/view?bvid=BV1if4y1g7Qp HTTP/1.1" 200 None

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/click/web/h5 HTTP/1.1" 200 32

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/web/heartbeat HTTP/1.1" 200 32

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/web/heartbeat HTTP/1.1" 200 32

观看视频成功🎉🎉

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/popular?ps=50&pn=1 HTTP/1.1" 200 None

获取 50 个视频成功🎉🎉

**Comment by ICE99125** [comment]
另外 Invoking task timed out after 3 seconds 只需要把超时时间增加一些就好了
![image](https://user-images.githubusercontent.com/65435402/146955767-5f9a877f-2834-4e0f-b6c5-ccf5444f984e.png)

**Comment by zhuzil** [comment]
感谢，还真是这个问题，我记得最开始的sleep时间是5秒，我改成了3秒，发现不行，我就以为不是这个了，没怎么用过腾讯云，不知道还能设置超时时间哈哈，学到了
