### ISSUE TITLE
pushplus无法推送信息

### ISSUE THREAD

**Issue by K032** [ICE99125/BiliBili_Checkin#5]
START RequestId: 1607c60f-ee94-4571-9502-ccd762507de7

Event RequestId: 1607c60f-ee94-4571-9502-ccd762507de7

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "GET /x/space/myinfo HTTP/1.1" 200 None

等级：lv5

硬币：82

经验：28704/28800

不进行观看...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/popular?ps=50&pn=1 HTTP/1.1" 200 None

获取 50 个视频成功🎉🎉

今日欲投0个硬币

投币完成,正在退出

正在分享视频...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/web-interface/share/add HTTP/1.1" 200 47

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/web-interface/share/add HTTP/1.1" 200 44

不启用漫画签到...

正在尝试直播签到...

Starting new HTTPS connection (1): api.live.bilibili.com:443

https://api.live.bilibili.com:443 "GET /sign/doSign HTTP/1.1" 200 86

直播签到失败,因为今日已签到过,无法重复签到

## Muon的Site

等级：lv5

硬币：82

经验：28704/28800

分享视频[]：完成

漫画未签到,因为：未启用

直播未签到,因为：今日已签到过,无法重复签到

Starting new HTTP connection (1): www.pushplus.plus:80

http://www.pushplus.plus:80 "POST /send HTTP/1.1" 200 None

END RequestId: 1607c60f-ee94-4571-9502-ccd762507de7

Report RequestId: 1607c60f-ee94-4571-9502-ccd762507de7 Duration:1018ms Memory:128MB MemUsage:16.75MB

**Comment by K032** [comment]
pushpuls可以正常接送其他函数的推送，已经重置pushpuls的key，无用

**Comment by ICE99125** [comment]
啥意思…

**Comment by ICE99125** [comment]
修复了
