### ISSUE TITLE
请问将分隔符改为特殊是什么意思

### ISSUE THREAD

**Issue by Anran0205** [ICE99125/BiliBili_Checkin#6]
云函数测试失败，是因为","的原因吗
-------------------------------------------------------------------

START RequestId: e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1

Init Report RequestId: e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1 Coldstart: 144ms (PullCode: 7ms InitRuntime: 5ms InitFunction: 132ms) Memory: 512MB MemUsage: 8.14MB

ERROR RequestId: e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 674, in exec_module   File "<frozen importlib._bootstrap_external>", line 781, in get_code   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1     import requests     ^ IndentationError: unexpected indent", "statusCode": 443}

END RequestId: e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1

Report RequestId: e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1 Duration: 0ms Memory: 512MB MemUsage: 8.14MB

START RequestId:e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1

ERROR RequestId:e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 674, in exec_module\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 781, in get_code\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 741, in source_to_code\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1\n    import requests\n    ^\nIndentationError: unexpected indent","statusCode":443}

END RequestId:e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1

Report RequestId:e7ea34e1-a8f9-47b5-9d5f-f2777c9092c1 Duration:0ms Memory:512MB MemUsage:0.000000MB

**Comment by ICE99125** [comment]
再试一下新的, 昨天改了一下出了点问题, 刚才改了

**Comment by Anran0205** [comment]
> 再试一下新的, 昨天改了一下出了点问题, 刚才改了
已解决，谢谢！
